version: '3.7'

services:
   web:
    build: ./src/
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./src/app/server:/usr/src/app/server
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
   db:
    image: kartoza/postgis:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
